service:
  name: tradle-mycloud-services

plugins:
  # - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  stage: dev
  environment:
    TABLE_NAME: 'tdl-superawesome-ltd-dev-bucket-0'
    S3_USER_LOG_PREFIX: 'tdl-superawesome-ltd-dev-logs/userlogs'
    S3_PATH_TO_PUSH_CONF: 'tdl-superawesome-ltd-dev-privconfbucket/conf/push-notifications.json'
    LOG_LEVEL: 'debug'
    AWS_REGION: ${self:provider.region}
    NOTIFY_LAMBDA_FUNCTION:
      Ref: NotifyLambdaFunction

  iamRoleStatements:

custom:
  region: 'us-east-1'
  serverless-offline:
    port: 31013

functions:
  # createPublisher:
  #   handler: lib/entrypoint/http/functions/root.handler
  #   events:
  #     - http:
  #         method: post
  #         path: publisher

  createPublisher:
    handler: lib/entrypoint/sns/functions/register-publisher.handler
    events:
      - sns: register-publisher

  createSubscriber:
    handler: lib/entrypoint/http/functions/root.handler
    events:
      - http:
          method: post
          path: subscriber

  createSubscription:
    handler: lib/entrypoint/http/functions/root.handler
    events:
      - http:
          method: post
          path: subscription

  notify:
    handler: lib/entrypoint/http/functions/root.handler
    events:
      - http:
          method: post
          path: notification

  clearBadge:
    handler: lib/entrypoint/http/functions/root.handler
    events:
      - http:
          method: post
          path: clearbadge

  saveUserLog:
    handler: lib/entrypoint/http/functions/root.handler
    events:
      - http:
          method: post
          path: userlog
