service:
  name: tradle-mycloud-services

plugins:
  # - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-offline
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  stage: dev
  baseEnvironment: &baseEnvironment
    MY_CLOUD_TABLE_NAME:
      Ref: MyCloudTableName
    S3_USER_LOGS_PREFIX:
      Ref: S3UserLogsPrefix
    S3_PATH_TO_PUSH_CONF:
      Ref: S3PushConfPath
    ACCOUNT_ID:
      Ref: AWS::AccountId
    LOG_LEVEL: 'debug'
  extendedEnvironment: &extendedEnvironment
    NOTIFY_LAMBDA_FUNCTION:
      Ref: NotifyLambdaFunction
  environment:
    <<: *baseEnvironment
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:AddPermission
        - sns:CreateTopic
        - sns:DeleteTopic
        - sns:Publish
        - sns:Subscribe
        - sns:Unsubscribe
        - sns:ListSubscriptions
        - sns:ListSubscriptionsByTopic
        - sns:GetTopicAttributes
        - sns:SetTopicAttributes
      Resource: '*'
    - Effect: Allow
      Action:
        - lambda:AddPermission
        - lambda:GetPolicy
      Resource:
        - Fn::Sub: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-*'
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:HeadObject
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3PushConfPath
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3UserLogsPrefix
              - '*'
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ''
            - - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/
              - Ref: MyCloudTableName
        - Fn::Join:
            - ''
            - - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/
              - Ref: MyCloudTableName
              - '/index/*'

  apiKeys:
    - privateServicesApiKey

custom:
  region: 'us-east-1'
  vars: ${file(./lib/config/index.js):createConfigFromEnv}
  serverless-offline:
    port: 31013
    noAuth: true

package:
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - .git/**
    - src/**
  excludeDevDependencies: true

functions:
  # PRIVATE API

  registerPublisher:
    handler: lib/entrypoint/http/functions/root.handler
    environment:
      <<: *extendedEnvironment
    events:
      - http:
          method: post
          path: pns/publisher
          # requires api key to access
          private: true

  # # PUBLISHER-PRIVATE API

  notify:
    handler: lib/entrypoint/sns/functions/notify.handler
    environment:
      <<: *baseEnvironment

  # # PUBLIC API (for subscribers)

  registerDevice:
    handler: lib/entrypoint/http/functions/root.handler
    environment:
      <<: *extendedEnvironment
    events:
      - http:
          method: post
          path: pns/subscriber

  subscribe:
    handler: lib/entrypoint/http/functions/root.handler
    environment:
      <<: *extendedEnvironment
    events:
      - http:
          method: post
          path: pns/subscription

  # clearBadge:
  #   handler: lib/entrypoint/http/functions/root.handler
  #   events:
  #     - http:
  #         method: post
  #         path: pns/clearbadge

  saveUserLog:
    handler: lib/entrypoint/http/functions/root.handler
    memorySize: 128
    environment:
      <<: *extendedEnvironment
    events:
      - http:
          method: post
          path: logs/userlog
          private: true

resources:
  Parameters:
    S3PushConfPath:
      Type: String
      Default: ${self:custom.vars.s3PushConfPath}
    S3UserLogsPrefix:
      Type: String
      Default: ${self:custom.vars.s3UserLogsPrefix}
    MyCloudTableName:
      Type: String
      Default: ${self:custom.vars.myCloudTableName}
